version: 0.2

phases:
  install:
    commands:
    # install Node 16.6
    - echo Installing Node 16...
    - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
    - apt install -y nodejs
  pre_build:
    commands:
      #install dependencies
      - echo Installing Dependencies...
      - npm install
  build:
    commands:
      # tests
      - echo Running Tests...
      - npm test
      # build
      - echo Running Build...
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: dist